<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us</title>
    <link rel="stylesheet" href="styles/aboutUsStyle.css">
    <?php include "navbar.phtml" ?>


</head>
<body>
<div class="wave"></div>
<div class="wave"></div>
<div class="wave"></div>
<div class="member-profiles">

    <div class="member-row">
        <div class="member"; style="width: auto">
            <img src="assets/blankprofile.png" alt="Member 1">
            <p><strong>First Name:</strong>Elizabetha</p>
            <p><strong>Last Name:</strong>Ondercin</p>
            <p><strong>Email:</strong>eondercin@mail.bradley.edu</p>
        </div>
    </div>


    <div class="member-row">
        <div class="member">
            <img src="assets/blankprofile.png" alt="Member 2">
            <p><strong>First Name:</strong>Cooper</p>
            <p><strong>Last Name:</strong>Denault</p>
            <p><strong>Email:</strong>cdenault@mail.bradley.edu</p>
        </div>

        <div class="member">
            <img src="assets/blankprofile.png" alt="Member 3">
            <p><strong>First Name:</strong> Thomas</p>
            <p><strong>Last Name:</strong> Janssen</p>
            <p><strong>Email:</strong> tjanssen@mail.bradley.edu</p>
        </div>
    </div>

    <!-- Two members side by side -->
    <div class="member-row">
        <div class="member">
            <img src="assets/blankprofile.png" alt="Member 4">
            <p><strong>First Name:</strong> Osvaldo</p>
            <p><strong>Last Name:</strong> Guzman</p>
            <p><strong>Email:</strong> oguzman@mail.bradley.edu</p>
        </div>

        <div class="member">
            <img src="assets/blankprofile.png" alt="Member 5">
            <p><strong>First Name:</strong> Tatyana</p>
            <p><strong>Last Name:</strong> Pacheco</p>
            <p><strong>Email:</strong> tpacheco@mail.bradley.edu</p>
        </div>
    </div>
</div>
<div class="overlay">
</body>
</html>
