<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project Info</title>
    <link rel="stylesheet" href="styles/aboutProjectStyle.css">
    <?php include "navbar.phtml" ?>
</head>
<body style="margin-top: 8%;">

    <h1>Project Info</h1>
    <div class ="center">
        <img src="assets/HFH_BG.jpeg"id="mainimage">
    </div>

    <h2>The goal of our project is to help Habitat for Humanity assist people who have existing homes restore any concerning areas. Our webpage will allow someone to upload photos from their home and add any modifications that are needed. It will also have an option of creating a project plan and allow the option to order materials or people to complete any assignments needed to update the house.</h2>

    <h1>Week 1 Progress</h1>
    <h2>Created Design elements for the project
        <ul>
            <li>Inputs (i.e., Image, Address, Annotation, etc.)</li>
            <li>Output success/error</li>
            <li>Began looking into database and security options</li>
        </ul>
    </h2>

    <h1>Week 2 Progress</h1>
    <h2>
        <ul>
            <li>Set up Discord and GitHub</li>
        </ul>
    </h2>

</body>
</html>