<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles/indexStyle.css">
    <script src="script.js"></script>
    <title>CS490</title>
</head>
<?php include "navbar.phtml" ?>

<body>
<div class="gradient"></div>
<h1 class="page-title">CS490|</h1>


<h1>Habitat for Humanity</h1>

<div class="gradient"></div>
<br>
</body>

</html>
